### ISSUE TITLE
[QUESTION] why terminfo is not installed?

### ISSUE THREAD

**Issue by robsonpeixoto** [wez/homebrew-wezterm-linuxbrew#4]
The alacritty recommends install the `terminfo` file to work correctly, but this Formula do not install it.

I'd like to know if is really important to install it for wezterm.

I did it to install terminfo "manually":
```bash
VERSION=$(wezterm --version | awk '{print $2}')
curl -O  https://raw.githubusercontent.com/wez/wezterm/$VERSION/termwiz/data/wezterm.terminfo
sudo /usr/bin/tic -xe wezterm wezterm.terminfo
```

Referencies:
- https://github.com/Homebrew/homebrew-cask/blob/master/Casks/alacritty.rb
- https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo

**Comment by wez** [comment]
It's not required to use wezterm.  Some programs want to find query terminfo before they will allow using some of the features that wezterm supports, so in those cases you may wish to install it (https://wezfurlong.org/wezterm/faq.html#how-do-i-enable-undercurl-curly-underlines)

If you'd like to submit a PR to install the terminfo for the brew install, that would be great!
(Also to the cask/recipe or whatever for wezterm that is in brew itself!)
